apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
    app: demo
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: mysql
    spec:
      containers:
      - image: mysql:latest
        args:
           - "--ignore-db-dir=lost+found"
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password

#       - name: MYSQL_ROOT_PASSWORD
#         valueFrom:
#           secretKeyRef:
#             name: mysql-pass
#             key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim


apiVersion: "v1"
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    app: demo
spec:
  containers:
    - name: mysql
      image: mysql:latest
      ports:
        - containerPort: 3306         
          protocol: TCP
      env: 
        - 
          name: "MYSQL_ROOT_PASSWORD"
          value: "password"
    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
    app: demo  
spec: 
  ports: 
    - name: mysql
      port: 3306
      targetPort: 3306
  selector: 
    name: mysql
    app: demo
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
    app: demo  
spec: 
  ports: 
    - name: mysql
      port: 3306
      targetPort: 3306
  selector: 
    run: mysql
--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: demo
    name: web
  name: web1
spec: 
  containers: 
    - image: redis
      name: redis
      ports: 
        - containerPort: 6379
          name: redis
          protocol: TCP
    - image: brunoterkaly/py-red
      name: python
      env: 
        - name: REDIS_HOST
          value: localhost
      ports: 
        - containerPort: 5000
          name: http
          protocol: TCP

apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  selector:
    name: web 
  type: LoadBalancer
  ports:
   - port: 80
     name: http
     targetPort: 5000
     protocol: TCP
